---
non_root_user: dandyrow

doas_conf_lines:
  - permit nopass root   # Allow root to run commands as other users with doas
  - permit persist :wheel

packages:
  - openssh
  - neovim
  - gcc
  - ripgrep
  - zellij
  - git
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - pkgfile
  - starship
  - neofetch
  - ttf-dejavu-nerd
  - noto-fonts-emoji
  - stow
  - exa
  - bat
  - sl
  - lf
  - gnupg
  - yamllint
  - npm
  - wget
  - tree-sitter
  - fd
  - wl-clipboard

dotfiles_to_install:
  - git
  - zsh
  - neofetch
  - starship
  - zellij
  - neovim

users:
  - name: dandyrow
    shell: /bin/zsh
    groups: wheel
    append: true
    password: "{{ dandyrow_password }}"  # Hand in password from ansible-playbook command
    dotfiles_repo: https://github.com/dandyrow/dotfiles
    dotfiles_repo_branch: master
    dotfiles_to_install:
      - zsh
      - zellij
      - neovim
      - starship
      - neofetch
      - git
  - name: root
    shell: /bin/bash
