---
version: "3.5"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true # Prevents processes inside the container gaining additional privileges.
    networks:
      proxy:
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 80:80
      - 81:81
      - 442:442
      - 443:443
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
    volumes:
      - traefik-ssl-certs:/ssl-certs
      - /home/dandyrow/podman/traefik/traefik.yml:/traefik.yml:ro
      - /home/dandyrow/podman/traefik/traefik-basic-auth:/traefik-basic-auth:ro
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.daniellowry.co.uk`)"
      - "traefik.http.routers.dashboard.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.dashboard-secure.rule=Host(`traefik.daniellowry.co.uk`)"
      - "traefik.http.routers.dashboard-secure.entrypoints=https-internal"
      - "traefik.http.routers.dashboard-secure.tls=true"
      - "traefik.http.routers.dashboard-secure.tls.certresolver=production"
      - "traefik.http.routers.dashboard-secure.tls.domains[0].main=daniellowry.co.uk"
      - "traefik.http.routers.dashboard-secure.tls.domains[0].sans=*.daniellowry.co.uk"
      - "traefik.http.routers.dashboard-secure.service=api@internal"

networks:
  proxy:
    name: proxy
    external: true

volumes:
  traefik-ssl-certs:
    driver: local
