---
- name: Install Gnome Desktop Environment on Arch Linux
  hosts: gnome
  tasks:
    - name: Install packages
      become: true
      become_method: doas
      community.general.pacman:
        name:
          - cups
          - flatpak
          - gdm
          - gnome-backgrounds
          - gnome-console
          - gnome-control-center
          - gnome-remote-desktop
          - gnome-online-accounts
          - gnome-shell
          - gnome-tweaks
          - gparted
          - gvfs
          - gvfs-goa
          - gvfs-gphoto2
          - gvfs-mtp
          - gvfs-nfs
          - gvfs-smb
          - hplip
          - mutter
          - nautilus
          - papirus-icon-theme
          - pacman-contrib
          - sushi
          - xdg-desktop-portal-gnome
          - xdg-user-dirs
          - xdg-user-dirs-gtk
          - xdg-utils
        state: present

    - name: Enable services
      become: true
      become_method: doas
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
      with_items:
        - gdm
        - cups

    - name: Ensure flathub remote is present
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user
        state: present

    - name: Install flatpaks
      community.general.flatpak:
        name:
          - org.gnome.baobab
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.clocks
          - org.gnome.Photos
          - org.gnome.SimpleScan
          - io.gitlab.librewolf-community
          - org.mozilla.Thunderbird
          - com.github.tchx84.Flatseal
          - com.mattjakeman.ExtensionManager
          - com.valvesoftware.Steam
          - net.lutris.Lutris
        method: user
        state: present

    - name: Enable Wayland Gnome on NVidia GPUs
      ansible.builtin.include_tasks: nvidia_wayland.yml
      when: nvidia | default(false)
