---
version: "3.5"
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - data:/app/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime-kuma.rule=Host(`uptime.daniellowry.co.uk`)
      - traefik.http.routers.uptime-kuma.entrypoints=https-internal
      - traefik.http.routers.uptime-kuma.tls=true
      - traefik.http.services.uptime-kuma.loadBalancer.server.port=3001

volumes:
  data:

networks:
  proxy:
    external: true
